// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFxkXr2NEPOuRgjMp3OeF86cwUztOXUN0',
    appId: '1:906297552907:web:343d0d7e0ef815631c970e',
    messagingSenderId: '906297552907',
    projectId: 'sportsapp-login',
    authDomain: 'sportsapp-login.firebaseapp.com',
    storageBucket: 'sportsapp-login.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxaUwHlYOOof8iYLNx8HAOv3gSWRaM8SI',
    appId: '1:906297552907:android:8ba0bf489fe67bee1c970e',
    messagingSenderId: '906297552907',
    projectId: 'sportsapp-login',
    storageBucket: 'sportsapp-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoEz-7xI7U_hqUkwuqRJV3V0lLFkRxJdk',
    appId: '1:906297552907:ios:fb0a024b1cdbb3101c970e',
    messagingSenderId: '906297552907',
    projectId: 'sportsapp-login',
    storageBucket: 'sportsapp-login.appspot.com',
    iosClientId: '906297552907-fe5c1km8hdsdknrpff1hl9m2ooekeda9.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoEz-7xI7U_hqUkwuqRJV3V0lLFkRxJdk',
    appId: '1:906297552907:ios:fb0a024b1cdbb3101c970e',
    messagingSenderId: '906297552907',
    projectId: 'sportsapp-login',
    storageBucket: 'sportsapp-login.appspot.com',
    iosClientId: '906297552907-fe5c1km8hdsdknrpff1hl9m2ooekeda9.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportTest',
  );
}
